[database]
url = "sqlite+aiosqlite:///data.db"
echo = false
pool_size = 10
max_overflow = 20
pool_recycle = 3600
pool_timeout = 30

[bot]
prefix = "."
temp_dir = "."
cogs = ["owner", "misc", "betting", "iq"]

[bot.owner]
id = 477506746986921992

[bot.intents]
guilds = true
messages = true
message_content = true
reactions = true

[[bot.whitelist]]
guild = 1361882687895371838
channel = 1361882688709198077
roles = []

[[bot.whitelist]]
guild = 789692030741774368
channel = 978273836338413648
roles = []

[gpt]
model = "gpt-4o"
max_tokens = 450

[gpt.history]
minutes = 30
messages = 100

[elo]
k = 32
max_delta = 50
scale = 400