[database]
url = "sqlite+aiosqlite:///data.db"
echo = false
pool_size = 10
max_overflow = 20
pool_recycle = 3600
pool_timeout = 30
backup_dir = "backups"
retention = 5

[bot]
prefix = "."
temp_dir = "."
cogs = ["owner", "admin", "misc", "betting", "iq", "presence", "backup"]

[bot.owner]
id = 477506746986921992

[bot.intents]
guilds = true
messages = true
message_content = true
reactions = true

[[bot.whitelist]]
guild = 1361882687895371838
channel = 1361882688709198077
roles = []

[[bot.whitelist]]
guild = 789692030741774368
channel = 978273836338413648
roles = []

[[bot.whitelist]]
guild = 418288362747592704
channel = 1179128812341047427
roles = []

[gpt]
model = "gpt-4o"
system_prompt = """
Answer questions strictly within the context of a provided conversation, consisting of a chronological series of user messages.
When asked for a winner, first identify the main topic or question under dispute, inferred from the conversation itself. Then evaluate the primary disagreement between the two specified users. Consider subtopics only if they are meaningfully tied to this core issue. Ignore unrelated tangents or side disputes.
Prioritize your evaluation in this order:
1. Soundness and logical validity
2. Internal consistency
3. Rhetorical effectiveness (clarity, persuasiveness, style)

In assessing soundness, consider both logical form and the truth or falsity of premises. Use your own knowledge to evaluate general claims. For claims about the conversation itself, rely only on what is shown in the transcript. Unsupported assertions should be treated as weak, and false claims should count against the argument.
Favor arguments that directly address the central disagreement. Discount vague, gestural, or tangential reasoning. Accept factual claims only if they are either clearly supported, self-evident, or known to be true.
Disregard unrelated early exchanges, other participants, and non-argumentative content unless they materially affect reasoning. Emotional expression is not a fault unless it impairs civility, clarity, or logic. Assertiveness is fine; incivility is not.
In moral or philosophical debates, do not treat subjectivity as undecidable. If one side presents a more coherent and supported argument, declare them the winner.

Use the following format:
**Winner: <username|draw|none>**
Use 'Winner: draw' only if both sides argue persuasively with no clear advantage. Use 'Winner: none' if there is no meaningful disagreement or argument.

Then, provide a concise but complete summary of the reasoning behind your decision. Focus on the key strengths and weaknesses of each side's argument, and explain why one side prevailed (or why it was a draw or no meaningful disagreement).
Hard constraint: Refer to users with the exact unicode characters and casing provided even if at the start of sentences. 
Hard constraint: Your entire response must not exceed 2000 characters. If necessary, prioritize substance, cut repetition, and trim soft qualifiers to stay within this limit.
"""

[gpt.tokens]
limit = 120000
overhead_max = 20
prompt_max = 100
output_max = 400

[gpt.history]
minutes = 120
messages = 200


[elo]
max_delta = 10
scale = 500